### PR TITLE
Clean up a bunch of stuff

### PR DESCRIPTION
**Pull request by shaunakw**
I ignored node_modules, so you'll have to add a build command to heroku (it's way better to add a build command instead of versioning all of node_modules, which is like 10000 files)

### CODE REVIEW

**Comment by OblivionGhoul** [comment]
Thanks, I still have a lot of refactoring to do haha.

**Comment by nathangong** [comment]
This pull request is objectively worse than the current iteration of the legendary KannaKamuiBot

**Comment by shaunakw** [comment]
> This pull request is objectively worse than the current iteration of the legendary KannaKamuiBot

How dare you

**Comment by shaunakw** [comment]
> Thanks, I still have a lot of refactoring to do haha. 

The point of the pull request is that I forked the repository and already did all the refactoring, so all you have to do is accept the pull request and my commits will be merged into your repository

**Comment by OblivionGhoul** [comment]
Yea I will, I just wanted to look at the changes first.

**Review by OblivionGhoul — APPROVED** [review]

**Review by OblivionGhoul — APPROVED** [review]

**Pull request closed without merging**
